{   'ae_autoquant'      : [['0', 'CNV', 'B1ir,R1234rs'], ['0', 'BN', 'BR1234c']],
   'ae_autoquantz'     : None,
   'ae_quant'          : None,
   'ae_quantz'         : None,
   'augment'           : 2,
   'batchsize'         : 128,
   'cz'                : False,
   'dataset'           : 'cifar10',
   'device'            : 0,
   'epoch'             : 300,
   'grad_approx'       : ['mean', '100', '10'],
   'learnrate'         : 0.05,
   'learnrate_decay'   : 70,
   'log_interval'      : 0.1,
   'model'             : 'resnet50',
   'momentum'          : 0.9,
   'out'               : 'rn50_autoquant',
   'resume'            : '',
   'seed'              : None,
   'snapshot_every'    : None,
   'update_interval'   : 20,
   'weight_decay'      : 0.0005,
}